# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_clamB-YqsJXRkUtUNilgeaXbx0Q7nm
"""

import tensorflow as tf
import matplotlib.pyplot as plt

mnist_stuff = tf.keras.datasets.mnist
(train_img, train_lab), (test_img, test_lab) = mnist_stuff.load_data()

train_img = train_img / 255.0
test_img = test_img / 255.0

the_brain = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])

the_brain.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print("traning the computer now...")
the_brain.fit(train_img, train_lab, epochs=3)

print("checking the accuracyy...")
the_brain.evaluate(test_img, test_lab)

num = 7
plt.imshow(test_img[num], cmap='gray')
plt.show()

final_guess = the_brain.predict(test_img[num:num+1]).argmax()
print("i think this is a:", final_guess)